export default {
  'Transfer': '在途',

  'StorageIn': '入库',
  'Procurement': '采购入库',
  'SalesIn': '销售退货',
  'CustomerStorageIn': '分销商退货',
  'TransferIn': '调拨入库',
  'OthersStorageIn': '其它入库',
  'WaitForStorageIn': '等待入库',
  'SectionStorageIn': '部分入库',
  'TotalStorageIn': '已入库',
  'Closed': '已关闭',
  
  'StorageOut': '出库',
  // 'Sales': '销售',
  'SalesOut': '销售出库',
  'CustomerStorageOut': '分销商出库',
  'WholesalesOut': '批发出库',
  'Refund': '采购退货',
  'TransferOut': '调拨出库',
  'OthersStorageOut': '其它出库',
  'WaitForStorageOut': '等待出库',
  'SectionStorageOut': '部分出库',
  'TotalStorageOut': '全部出库',

  'WaitForCheck': '等待盘点',
  'Checking': '盘点中',
  'CheckOut': '盘点结束',
  'checkUpdate': '盘点更新',

  'Normal': '正常',
  'Forbidden': '禁用',
  'Expired': '已过期',
  'Done': '完成',
  'Cancel': '取消',
  'Draft':'草稿',
  'Publish': '已发布',
  'Deprecated':'已下架',
  'PublishArticle':'已发布',
  'Wait_Audit':'待审核',
  'Audit_Rejected':'审核拒绝',
  'Wait_To_Audit':'待审核',
  'Audit_Passed':'审核通过',
  // 订单相关
  'SELF_PICK':'自提',
  'FLASH':'极速送达',
  'CREATED_PAY_PENDING': '待支付',
  'CLOSED_PAY_TIMEOUT': '支付超时关闭',
  'CLOSED_CANCELED': '已取消',
  'PAID_CONFIRM_PENDING': '已支付',
  'CONFIRMED_DELIVER_PENDING': '待发货',
  'CONFIRMED_PICK_PENDING': '待取货',
  'DELIVERING': '发货中',
  'DELIVERED_CONFIRM_PENDING': '已发货',
  'CANCELED_RETURN_PENDING': '待退货',
  'CLOSED_CONFIRMED': '已确认收货',
  'CANCELED_REFUND_PENDING': '待退款',
  'CLOSED_REFUNDED': '已退款',

  'ORIGINAL_PATH': '原路退款',
  'ORTHER_WAY': '其它方式',
  // 预约相关
  'PAY_PENDING':'待付款',
  'PAY_TIMEOUT': '取消支付',
  // 'PAYMENT_CANCELLED': '未支付',
  'WAIT_TO_STORE': '待到店',
  'ALREADY_TO_STORE': '已到店',
  'MISS_TO_STORE': '失约未到店',
  'CANCELLED': '已取消',
  'EXPIRED': '过期未处理',

  // 交班
  'APPLYING': '待接班人确认',
  'CONFIRM': '已确认',

  // 支付方式
  'WECHAT': '微信',
  'ALIPAY': '支付宝',
  'CASH': '现金',
  'WALLET': '钱包',
  'CARD': '银行卡',

  'CHARGE': '充值',
  'PAY': '支付',
  'GIFT': '赠送',
  'WITHDRAW': '转入零钱',
  'REFUND': '退款',

  'BUSINESS': '正在营业',
  'REST': '休息',
  'CLOSED': '关闭',

  'NOT_ACTIVATION': '未激活',
  'ACTIVATION': '已激活',
  'OVERDUE': '已过期',
  'USED': '已使用',
};